version: 2.1

orbs:
  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2
  gcp-gcr: circleci/gcp-gcr@0.11.0
  discord: 
    commands:
      log_fail:
        steps:
          - run:
              name: Log failure to Discord
              when: on_fail
              command: |
                curl --header "Content-Type: application/json" \
                --request POST \
                --data "{\"owner\":\"${CIRCLE_PROJECT_USERNAME}\",\"status\":\"fail\",\"build\":{\"url\":\"$CIRCLE_BUILD_URL\"},\"repo\":\"$CIRCLE_PROJECT_REPONAME\"}" \
                https://enm80iuzvo27wof.m.pipedream.net
      log:
        steps:
          - run:
              name: Log failure to Discord
              when: on_fail
              command: |
                curl --header "Content-Type: application/json" \
                --request POST \
                --data "{\"owner\":\"${CIRCLE_PROJECT_USERNAME}\",\"status\":\"fail\",\"build\":{\"url\":\"$CIRCLE_BUILD_URL\"},\"repo\":\"$CIRCLE_PROJECT_REPONAME\"}" \
                https://enm80iuzvo27wof.m.pipedream.net
          - run: 
              name: Log success to Discord
              when: on_success
              command: |
                curl --header "Content-Type: application/json" \
                --request POST \
                --data "{\"owner\":\"${CIRCLE_PROJECT_USERNAME}\",\"status\":\"success\",\"build\":{\"url\":\"$CIRCLE_BUILD_URL\"},\"repo\":\"$CIRCLE_PROJECT_REPONAME\"}" \
                https://enm80iuzvo27wof.m.pipedream.net


jobs:
  build:
    docker:
    - image: cimg/node:14.15
    steps:
    - checkout
    - run: yarn add @angular/cli
    - run: yarn ng build --prod
    - persist_to_workspace:
        root: ./
        paths:
          - "dist"
          - "Dockerfile"
    - discord/log_fail
  publish:
    docker:
    - image: cimg/base:2020.11
    resource_class: small
    steps:
    - attach_workspace:
        at: ./
    - setup_remote_docker:
        version: 18.09.3
        docker_layer_caching: false
    - gcp-gcr/gcr-auth
    - run: |
        TAG=$VERSION.$CIRCLE_BUILD_NUM
        docker build -t $REPO:$TAG .
        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        docker tag $REPO:$TAG $REPO:latest
        docker push $REPO:$TAG
        docker push $REPO:latest
        docker tag $REPO:$TAG gcr.io/$GOOGLE_PROJECT_ID/angular-calculator:$CIRCLE_SHA1
    - gcp-gcr/push-image:
        image: angular-calculator
        tag: $CIRCLE_SHA1
    - discord/log_fail
  deploy:
    docker: 
    - image: cimg/base:2020.11
    resource_class: small
    steps:
    - gcp-cloud-run/init
    - gcp-cloud-run/deploy:
        image: gcr.io/$GOOGLE_PROJECT_ID/angular-calculator:$CIRCLE_SHA1
        platform: managed
        region: europe-north1
        service-name: angular-calculator
        unauthenticated: true
    - discord/log

workflows:
  regular:
    jobs:
    - build
    - publish:
        requires:
          - build
    - deploy:
        requires:
          - publish