version: 2.1

orbs:
  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2
  gcloud: circleci/gcp-cli@2.1.0

jobs:
  build:
    docker:
    - image: cimg/node:14.15
    steps:
    - checkout
    - run: yarn add @angular/cli
    - run: yarn ng build --prod
    - persist_to_workspace:
        root: ./
        paths:
          - "dist"
          - "Dockerfile"
  publish:
    docker:
    - image: cimg/base:2020.11
    resource_class: small
    steps:
    - attach_workspace:
        at: ./
    - setup_remote_docker:
        version: 18.09.3
        docker_layer_caching: false
    - gcloud/install
    - run: |
        TAG=$VERSION.$CIRCLE_BUILD_NUM
        docker build -t $REPO:$TAG .
        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        docker tag $REPO:$TAG $REPO:latest
        docker push $REPO:$TAG
        docker push $REPO:latest
        echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
        gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
        gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
        gcloud auth configure-docker
        docker tag $REPO:$TAG gcr.io/${GOOGLE_PROJECT_ID}/angular-calculator-${CIRCLE_SHA1}
        docker push gcr.io/${GOOGLE_PROJECT_ID}/angular-calculator-${CIRCLE_SHA1}
    - run: 
        command: |
          curl --header "Content-Type: application/json" \
          --request POST \
          --data "{\"owner\":\"${CIRCLE_PROJECT_USERNAME}\",\"status\":\"success\",\"build\":{\"url\":\"$CIRCLE_BUILD_URL\"},\"repo\":\"$CIRCLE_PROJECT_REPONAME\"}" \
          https://enm80iuzvo27wof.m.pipedream.net
        when: on_success
    - run: 
        command: |
          curl --header "Content-Type: application/json" \
          --request POST \
          --data "{\"owner\":\"${CIRCLE_PROJECT_USERNAME}\",\"status\":\"fail\",\"build\":{\"url\":\"$CIRCLE_BUILD_URL\"},\"repo\":\"$CIRCLE_PROJECT_REPONAME\"}" \
          https://enm80iuzvo27wof.m.pipedream.net
        when: on_fail
  deploy:
    docker: 
    - image: cimg/base:2020.11
    resource_class: small
    steps:
      - gcp-cloud-run/init
      - gcp-cloud-run/deploy:
          image: gcr.io/${GOOGLE_PROJECT_ID}/angular-calculator-${CIRCLE_SHA1}
          platform: managed
          region: europe-north1
          service-name: angular-calculator-00001-nir
          unauthenticated: true

workflows:
  regular:
    jobs:
    - build
    - publish:
        requires:
          - build
    - deploy:
        requires:
          - publish